export const ESPECIALIDADES_MEDICAS = [
  "Medicina General",
  "Medicina Interna",
  "Medicina Familiar",
  "Pediatría",
  "Cirugía General",
  "Cirugía Cardiovascular",
  "Cirugía Plástica y Reconstructiva",
  "Cirugía Pediátrica",
  "Traumatología y Ortopedia",
  "Ginecología y Obstetricia",
  "Cardiología",
  "Dermatología",
  "Endocrinología",
  "Gastroenterología",
  "Geriatría",
  "Hematología",
  "Infectología",
  "Nefrología",
  "Neumología",
  "Neurología",
  "Neurocirugía",
  "Oftalmología",
  "Oncología Médica",
  "Otorrinolaringología",
  "Psiquiatría",
  "Psiquiatría Infantil y del Adolescente",
  "Radiología",
  "Reumatología",
  "Urología",
  "Anestesiología",
  "Medicina Física y Rehabilitación",
  "Medicina del Deporte",
  "Medicina de Urgencia",
  "Inmunología Clínica y Alergia",
  "Genética Clínica",
  "Patología Clínica",
  "Anatomía Patológica",
  "Medicina Nuclear",
  "Radioterapia Oncológica",
  "Coloproctología",
  "Cirugía de Tórax",
  "Cirugía Maxilofacial",
  "Diabetología",
  "Neonatología",
  "Nutriología",
  "Medicina Intensiva",
];
